### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by nawazdj** [artifactdev/Theme-Dark-Material#1]
It shows error:

Error trying to parse settings: Expected value in Packages\User\Preferences.sublime-settings:6:2

**Comment by artifactdev** [comment]
Can you please post your Preferences.sublime-settings?

**Comment by nawazdj** [comment]
![capture](https://cloud.githubusercontent.com/assets/5891153/8267394/f9c23ee4-1781-11e5-9eb5-1788f8cb7f4e.PNG)

**Comment by nawazdj** [comment]
![capture](https://cloud.githubusercontent.com/assets/5891153/8267408/73ab1ef6-1782-11e5-9b59-2dba60e96e8c.PNG)

**Comment by artifactdev** [comment]
Please have a look when the update appears in Package Control.

But also your settings file seems to be broken.

Follow the new path instructions in the readme and delete the following lines:

[
    "Vintage"
]

Than the theme should work correctly.

**Comment by nawazdj** [comment]
It's working now, thanks.

**Comment by cristianeto** [comment]
Please Help

<img width="1280" alt="captura de pantalla 2015-07-04 a las 0 29 30" src="https://cloud.githubusercontent.com/assets/9989801/8506628/e01b3164-21e3-11e5-9dd4-b7c31c2c0035.png">
