### ISSUE TITLE
Same color on AdvanceNewFile and Vintageous bars

### ISSUE THREAD

**Issue by mammut** [artifactdev/Theme-Dark-Material#2]
Hello,

when using the AdvanceNewFile or Vintageous plugins, there is a command bar that pops up, on the theme it seems to be missing because the text and background have the same color.

![screen_shot_2015-06-19_at_12_10_25_pm](https://cloud.githubusercontent.com/assets/802770/8256296/914aff6e-167c-11e5-9d12-179628c60551.png)

Thank you.

**Comment by artifactdev** [comment]
Are you using Sublime Text 2?

**Comment by mammut** [comment]
Sublime Text 3, build 3083

**Comment by mammut** [comment]
It's there, just can't see the text

![screen_shot_2015-06-19_at_12_22_06_pm](https://cloud.githubusercontent.com/assets/802770/8256515/f2e167d0-167d-11e5-892d-3626f93ebce8.png)

**Comment by artifactdev** [comment]
So can you explain hot to get to this bar? I tried it with vintageous but it seems to work.

![vitageous-screen](https://cloud.githubusercontent.com/assets/856013/8271762/35aea1ee-1828-11e5-8adb-553f146682f4.jpg)

**Comment by digiltd** [comment]
I have the same problem. 

Not sure if it is a default keybinding but I use CMD+SHIFT+R to bring up the Advanced New File panel at the bottom.

You can also get to it through the Command Pallet under ANF:Rename

It usually appears like the regular find/find and replace panels do.

The other material theme also has this problem.

**Comment by digiltd** [comment]
Ah ha, managed to fix it. If i hovered over where the panel break would be after activating it, I was able to drag up what seemed like nothing. Then the bar popped into view and works as normal.

Here is a crude photo or rollover thingy if it helps others or yourself isolate the bug.

![image](https://cloud.githubusercontent.com/assets/5680968/8327978/b0b6d616-1a64-11e5-9e33-ead1ad468b14.png)

**Comment by mammut** [comment]
aha! perfect! that solved my problem. Thank you @digiltd
