### ISSUE TITLE
Some images not showing correctly

### ISSUE THREAD

**Issue by sallomendo** [artifactdev/Theme-Dark-Material#3]
I installed the latest version manually and can get it to work properly, btw I love the theme and really want to use it :(

![screen shot 2015-06-19 at 1 25 16 pm](https://cloud.githubusercontent.com/assets/698122/8260019/a7765630-1686-11e5-8f80-8a4755706b01.png)

**Comment by mammut** [comment]
I had this problem when I installed it from Package Manager. So I downloaded it manually and put it on the Packages folder. But the plugin folder name MUST be **Theme-Dark-Material\* if it's something like **Theme-Dark-Material-1.0.0** it won't work.

**Comment by sallomendo** [comment]
Thanks! I got it working! :+1:
