### ISSUE TITLE
Theme failed

### ISSUE THREAD

**Issue by whatifhappen** [artifactdev/Theme-Dark-Material#5]
After I'd installed the theme it popup with this message, and the colors are all went wrong. I'd uninstalled it and reinstall with manual still get the same error. I'm currently using Build 3083.
![image](https://cloud.githubusercontent.com/assets/4222249/8269097/73196a7e-17cd-11e5-83a2-57a52abb6acf.png)

**Comment by artifactdev** [comment]
That should be fixed now. An update will appear in Package Control and it should be fixed by adding the right paths (see the updated readme)
