### ISSUE TITLE
SideBarEnhancements input fields are not visible

### ISSUE THREAD

**Issue by a-type** [artifactdev/Theme-Dark-Material#7]
Since installing this theme (which looks wonderful, well done!), the input fields for the [SideBarEnhancements](https://packagecontrol.io/packages/SideBarEnhancements) package have not been showing up. This makes it difficult to create a new file or folder, and next to impossible to move files. Haven't had time to look under the hood yet, but I thought I'd at least let you know.

**Comment by artifactdev** [comment]
I pushed a new release (1.0.3) to the package manager. Maybe this could fix your error. If not a workaround is to put the cursor above the statusbar until it changes than move it up. The rename box is there but "minified".

**Comment by a-type** [comment]
Ah, I see. I actually found the same solution from the readme in the [Material Theme](https://github.com/equinusocio/material-theme) repo, which I noticed this was based on. Might be a good idea to include it in your readme as well, since it seems to be affecting other users ( #8 ).

**Comment by a-type** [comment]
For future reference, the solution is indeed to hover around where the input fields should be, until the cursor becomes a vertical resize cursor. Grab the invisible border and expand the input fields manually. It seems that the size is persistent, so you only need to do it once. Can probably close this issue.

**Comment by equinusocio** [comment]
@a-type https://github.com/artifactdev/Theme-Dark-Material/issues/9
