### ISSUE TITLE
Reference please.

### ISSUE THREAD

**Issue by equinusocio** [artifactdev/Theme-Dark-Material#9]
Please reference the original [Material Theme](https://github.com/equinusocio/material-theme). This is identical. Open Source doesn't mean "steal and re-plublish".

<img width="1053" alt="screen shot 2015-08-20 at 19 14 30" src="https://cloud.githubusercontent.com/assets/10454741/9443655/8416e0b2-4a82-11e5-9c20-a954a6440e8d.png">

**Comment by artifactdev** [comment]
Sorry I will add an advice by today.

**Comment by artifactdev** [comment]
Added the reference, sorry it was my fault that I doesn't included it 'til now. Hopefully it's ok so?

**Comment by equinusocio** [comment]
Also in the README please. Like https://github.com/silvestreh/atom-material-ui

**Comment by artifactdev** [comment]
It's already in the readme too

**Comment by equinusocio** [comment]
Thanks.
